#PBS -N ddp
#PBS -l select=2:ncpus=20:mem=120gb:ngpus=2:gpu_model=p100
#PBS -l walltime=00:10:00
#PBS -j oe

module add gnu-parallel/20200722

set -x

cd $PBS_O_WORKDIR

master_ip=`hostname -I | awk '{print $1}'`
data_path="/zfs/citi/datasets/mnist/"
count=$(sort -u $PBS_NODEFILE | wc -l) 

seq ${count} | parallel --jobs 1 --sshloginfile $PBS_NODEFILE --workdir $PWD "./run_torch.sh $PBS_O_WORKDIR {} $master_ip $data_path $count" 
